### ISSUE TITLE
Add link to go to top of page in README.md

### ISSUE THREAD

**Issue by elenajp** [hackerkid/Mind-Expanding-Books#380] opened 2021-10-05 08:39 UTC
Hi 👋🏻

I think it would be nice to have links after each book category in the README.md file to save the user from having to scroll all the way up to the top. If you would also like this then I am happy to add it. Let me know 😊

**Comment by elenajp** [comment] 2021-10-07 12:25
Looks like you have worked on it haha but sure go for it if the repo owner is happy with my idea and wishes to implement it 😀

**Comment by Yashpd** [comment] 2021-10-08 16:57
Oh I'm sorry if you had plans to work on this issue. I did not realise that. i just saw an open issue, so I went ahead and made the changes.

**Comment by elenajp** [comment] 2021-10-09 08:15
haha all good, it is nice that you made the contribution.

**Comment by AshwiniDR1802** [comment] 2022-10-07 16:34
i want to contribute

**Comment by varadrane7** [comment] 2023-08-14 14:59
It seems the issue is still open, can you assign this to me, ill add it after every section table.

**Comment by hackerkid** [comment] 2023-08-28 17:58
Closed since fixed.

**Closed by hackerkid** 2023-08-28 17:58 UTC
